#!/bin/bash

# get full script path so nothing breaks in case we call it from a different place
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# load into app root dir if YPT_YOUTUBE_DL_PATH is not set
if [[ -z $YPT_YOUTUBE_DL_PATH ]]; then
	YOUTUBE_DL_PATH="$DIR/youtube-dl"
else
	YOUTUBE_DL_PATH=$YPT_YOUTUBE_DL_PATH
fi

if [[ ! -e $YOUTUBE_DL_PATH ]]; then
	echo "youtube-dl not found"
	echo "Downloading latest version to $YOUTUBE_DL_PATH"
	curl -Ls "https://yt-dl.org/downloads/latest/youtube-dl" -o $YOUTUBE_DL_PATH
	echo "Download finished. Don't forget to make the file executable!"
	exit 0
else
	echo "Checking for latest version..."
fi

# first we get the latest release tag
LATEST_RELEASE_TAG=$(curl -LIs -o /dev/null -w %{url_effective} https://github.com/ytdl-org/youtube-dl/releases/latest/ | cut -d/ -f8)
# then we create the downloads url with this tag
LATEST_RELEASE_DOWNLOADS_URL="https://github.com/ytdl-org/youtube-dl/releases/download/$LATEST_RELEASE_TAG"
# now we pull the latest checksums
LATEST_CHECKSUM=$(curl -Ls "$LATEST_RELEASE_DOWNLOADS_URL/MD5SUMS" | head -1 | cut -d ' ' -f1)
# calculate the old one
CURRENT_CHECKSUM=$(md5sum $YOUTUBE_DL_PATH | cut -d ' ' -f1)

echo "Checksums"
echo "Local: $CURRENT_CHECKSUM"
echo "Latest: $LATEST_CHECKSUM"

# and compare them
diff <(echo $CURRENT_CHECKSUM) <(echo $LATEST_CHECKSUM)

if [[ $? -eq 1 ]]; then
	echo "Checksum changed. Downloading latest version to $YOUTUBE_DL_PATH"
	curl -Ls "$LATEST_RELEASE_DOWNLOADS_URL/youtube-dl" -o $YOUTUBE_DL_PATH
	echo "Download finished."
else
	echo "Nothing changed."
fi
